- block:
  - name: Add Docker GPG apt Key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc 
      mode: 0644
      force: true
    become: true
  - name: Add Docker Repository
    apt_repository:
      repo: deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
      state: present
    become: true
  tags: 
    - docker
    - install
    - packages
    - apt
  when: ansible_os_family == "Debian"