- block:
    - name: Ensure Hyprland and related official packages are installed
      pacman:
        name:
          - hyprland
          - waybar
          - mako
          - swaybg
          - libqalculate
          - swayosd
          - xdg-desktop-portal-hyprland
          - xdg-desktop-portal-gtk
        state: present
        update_cache: yes
      become: true

    - name: Ensure Hyprland AUR packages are installed
      kewlfft.aur.aur:
        name:
          - hyprshot
          - hyprpicker
          - hyprlock
          - hypridle
          - polkit-gnome
          - walker-bin
          - hyprland-qtutils
        state: present

    - name: Start Hyprland on first session in .bash_profile
      blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.bash_profile"
        block: |
          if uwsm check may-start -q; then
              exec uwsm start hyprland-uwsm.desktop
          fi
        state: present
        create: yes

    - name: Start Hyprland on first session in .zprofile
      blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.zprofile"
        block: |
          if uwsm check may-start -q; then
              exec uwsm start hyprland-uwsm.desktop
          fi
        state: present
        create: yes

  when: ansible_os_family == "Archlinux"
  tags:
    - hyprland
    - install
    - packages
