- block:
    - name: Update the user desktop database
      command: update-desktop-database {{ lookup('env','HOME') }}/.local/share/applications

    - name: Set imv as default for images (png, jpeg, gif, webp, bmp, tiff)
      shell: |
        xdg-mime default imv.desktop image/png
        xdg-mime default imv.desktop image/jpeg
        xdg-mime default imv.desktop image/gif
        xdg-mime default imv.desktop image/webp
        xdg-mime default imv.desktop image/bmp
        xdg-mime default imv.desktop image/tiff
      args:
        executable: /bin/bash

    - name: Set Evince as default for PDFs
      command: xdg-mime default org.gnome.Evince.desktop application/pdf

    - name: Set Chromium as the default browser
      shell: |
        xdg-settings set default-web-browser chromium.desktop
        xdg-mime default chromium.desktop x-scheme-handler/http
        xdg-mime default chromium.desktop x-scheme-handler/https
      args:
        executable: /bin/bash

    - name: Set mpv as default for video files
      shell: |
        xdg-mime default mpv.desktop video/mp4
        xdg-mime default mpv.desktop video/x-msvideo
        xdg-mime default mpv.desktop video/x-matroska
        xdg-mime default mpv.desktop video/x-flv
        xdg-mime default mpv.desktop video/x-ms-wmv
        xdg-mime default mpv.desktop video/mpeg
        xdg-mime default mpv.desktop video/ogg
        xdg-mime default mpv.desktop video/webm
        xdg-mime default mpv.desktop video/quicktime
        xdg-mime default mpv.desktop video/3gpp
        xdg-mime default mpv.desktop video/3gpp2
        xdg-mime default mpv.desktop video/x-ms-asf
        xdg-mime default mpv.desktop video/x-ogm+ogg
        xdg-mime default mpv.desktop video/x-theora+ogg
        xdg-mime default mpv.desktop application/ogg
      args:
        executable: /bin/bash

  when: ansible_os_family == "Archlinux"
  tags:
    - install
    - mimetypes
