- block:
    - name: Ensure application directory exists for update-desktop-database
      file:
        path: "{{ lookup('env','HOME') }}/.local/share/applications"
        state: directory
        mode: "0755"

    - name: Create systemd override directory for autologin
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
        mode: "0755"
      become: yes

    - name: Set up autologin for current user on tty1
      copy:
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=-/usr/bin/agetty --autologin {{ lookup('env','USER') }} --noclear %I $TERM
        owner: root
        group: root
        mode: "0644"
      become: yes

    - name: Write ~/.XCompose with Omarchy includes and ID
      copy:
        dest: "{{ lookup('env','HOME') }}/.XCompose"
        content: |
          include "%H/.local/share/omarchy/default/xcompose"

          # Identification
          <Multi_key> <space> <n> : "{{ lookup('env','OMARCHY_USER_NAME') | default('') }}"
          <Multi_key> <space> <e> : "{{ lookup('env','OMARCHY_USER_EMAIL') | default('') }}"
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "0644"

  when: ansible_os_family == "Archlinux"
