---
- name: Include brew taps list
  include_vars: vars/brew-taps.yml
  tags:
    - apt
    - packages
    - install

- name: Include brew formula list
  include_vars: vars/brew-formula.yml
  tags:
    - apt
    - packages
    - install

- name: Include brew casks list
  include_vars: vars/brew-casks.yml
  tags:
    - apt
    - packages
    - install

- name: Include APT package list
  include_vars: vars/apt.yml
  tags:
    - apt
    - packages
    - install

- name: Include python package list
  include_vars: vars/pip.yml
  tags:
    - apt
    - packages
    - install

- block:
  - name: Update/Upgrade Homebrew
    homebrew:
      update_homebrew: true
      upgrade_all: true

  - name: Manage taps
    homebrew_tap:
      name: "{{ item }}"
      state: "{{ item.value.state | default('present') }}"
    with_list: "{{ taps }}"

  - name: Manage formula
    homebrew:
      name: "{{ item }}"
      install_options: "{{ item.value.options | default(omit) }}"
      state: "{{ item.value.state | default('present') }}"
    with_list: "{{ formulas }}"

  - name: Manage casks
    homebrew_cask:
      name: "{{ item }}"
      state: "{{ item.value.state | default('present') }}"
    with_list: "{{ casks }}"

  - name: Manage alacritty (requires no-quarantine)
    homebrew_cask:
      name: "alacritty"
      state: "present"
      install_options: "no-quarantine"

  - name: Start Syncthing service
    command: brew services start syncthing

  when: ansible_os_family == "Darwin"
  tags: 
    - brew
    - install
    - packages

- block:
  - name: Update/Upgrade apt
    apt:
      update_cache: true
      upgrade: dist
  - name: Add user to Docker group
    user:
      name: "{{ ansible_env.USER }}"
      groups: docker
      append: yes
  - name: Manage apt packages
    apt:
      name: "{{ apt }}"
      state: latest

  - name: Download Nim-lang initialization script
    get_url:
      url: https://nim-lang.org/choosenim/init.sh
      dest: /tmp/init.sh
      mode: '0755'

  - name: Execute Nim-lang initialization script
    shell: sh /tmp/init.sh -y
    args:
      executable: /bin/sh

  - name: Enable Syncthing service for local user
    systemd:
      name: syncthing@{{ username }}.service
      enabled: yes

  - name: Start Syncthing service for local user
    systemd:
      name: syncthing@{{ username }}.service
      state: started

  become: true
  when: ansible_os_family == "Debian"
  tags: 
   - packages
   - apt
   - install

- name: Manage python packages
  pip:
    name: "{{ item }}"
    state: "{{ item.value.state | default('latest') }}"
    executable: "{{ item.value.executable | default('pip3') }}"
  with_list: "{{ pip }}"
  tags:
    - install
    - pip
    - packages

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    update: yes
  tags:
    - install
    - packages
    - tmux
