- name: Ensure .secret directory exists.
  file:
    dest: "{{ secret_dir }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - secrets
- name: Install all secrets as defined in vars/secrets.yml
  include_vars: vars/secrets.yml
  copy:
    src: ".secrets/{{ item.name }}"
    dest: "{{ lookup('env', 'HOME') }}/.secrets/{{ item.name }}"
    mode: 0600
  loop: "{{ files_to_copy }}"
  tags:
    - dotfiles
    - install
    - secrets

