- name: Include secret vars
  include_vars: vars/secrets.yml
  tags:
    - dotfiles
    - install
    - secrets

- name: Ensure .secret directory exists.
  file:
    dest: "{{ secret_dir }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - secrets
- name: Check if secrets already exist
  stat:
    path: "{{ secret_dir }}/{{ item.name }}"
  register: secret_stat
  loop: "{{ secrets }}"
  tags:
    - dotfiles
    - install
    - secrets

- name: Install all secrets as defined in vars/secrets.yml
  copy:
    src: "{{ dotfiles_dir }}/.secrets/{{ item.item.name }}"
    dest: "{{ secret_dir }}/{{ item.item.name }}"
    mode: 0600
  loop: "{{ secret_stat.results }}"
  when: not item.stat.exists
  tags:
    - dotfiles
    - install
    - secrets
