- name: Include secret vars
  include_vars: vars/secrets.yml
  tags:
    - dotfiles
    - install
    - secrets

- name: Ensure .secret directory exists.
  file:
    dest: "{{ secret_dir }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - secrets
- name: Install all secrets as defined in vars/secrets.yml
  copy:
    src: "{{ dotfiles_dir }}/.secrets/{{ item.name }}"
    dest: "{{ secret_dir }}/{{ item.name }}"
    mode: 0600
  loop: "{{ secrets }}"
  tags:
    - dotfiles
    - install
    - secrets
