- block:
    - name: Download Starship install script
      get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/install_starship.sh
        mode: '0755'

    - name: Execute Starship install script
      command: sh /tmp/install_starship.sh
      become: true

  when: ansible_os_family == "Debian"
