- name: Copy wsl.conf to /etc/wsl.conf
  copy:
    src: "{{ dotfiles_dir }}/configs/wslconf/wsl.conf"
    dest: /etc/wsl.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  when: ansible_os_family == "Debian"
  tags:
    - wsl
    - install
