- block:
    - name: Ensure base-devel and git are installed
      pacman:
        name:
          - base-devel
          - git
        state: present
        update_cache: yes
      become: yes

    - name: Clone yay from AUR
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: "{{ lookup('env', 'HOME') }}/yay"
        clone: yes
        update: yes

    - name: Build and install yay
      command: makepkg -si --noconfirm
      args:
        chdir: "{{ lookup('env', 'HOME') }}/yay"

    - name: Remove yay build directory
      file:
        path: "{{ lookup('env', 'HOME') }}/yay"
        state: absent
  when: ansible_os_family == "Archlinux"
  tags:
    - install
    - yay
