- block:
    - name: Install ZSH
      apt: name=zsh
      tags: &tags_for_zsh_tasks ["install", "dotfiles", "zsh"]
      when: ansible_os_family == "Debian"
      become: true

    - name: Change shell to zsh
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      tags: *tags_for_zsh_tasks
      become: true
      when: ansible_os_family == "Debian"

    - name: Check that the oh-my-zsh config exists
      stat:
        path: /home/{{ ansible_user_id }}/.oh-my-zsh
      register: oh_my_stats
      tags: *tags_for_zsh_tasks

    - name: Oh-My-Zsh
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
      tags: *tags_for_zsh_tasks
      when:
        oh_my_stats.stat.exists == False
        # become_user: "{{ ansible_user_id }}"

    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      tags: *tags_for_zsh_tasks

    - name: Install zsh-syntax-highlighting
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      tags: *tags_for_zsh_tasks

    - name: Install zsh-completions
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-completions.git"
        dest: "~/.oh-my-zsh/custom/plugins/zsh-completions"
      tags: *tags_for_zsh_tasks

    - name: Install fzf-zsh-plugin
      ansible.builtin.git:
        repo: "https://github.com/unixorn/fzf-zsh-plugin.git"
        dest: "~/.oh-my-zsh/custom/plugins/fzf-zsh-plugin"
      tags: *tags_for_zsh_tasks

  when: ansible_os_family in ["Debian", "Darwin"]
