- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    secret_dir: "{{ lookup('env', 'HOME') }}/.secrets" 
    personal: "{{ lookup('env', 'HOME') }}/personal"
    work: "{{ lookup('env', 'HOME') }}/work"
    username: "{{ lookup('env', 'USER') }}"
  pre_tasks:
  - name: Update Apt
    when: ansible_os_family == "Debian"
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/packages.yml
    - include: tasks/mamba.yml
      when: ansible_os_family == "Debian"
    - include: tasks/nvim.yml
      when: ansible_os_family == "Debian"
    - include: tasks/stow.yml
    - include: tasks/zsh.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
  roles:
    - role: ecgalaxy.vscode
      include_vars:
        file: vars/vscode_extensions.yml
