- hosts: localhost
  vars:
    source_key: "{{ lookup('env', 'HOME') }}/.dotfiles/.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    ssh_dir: "{{ lookup('env', 'HOME') }}/.ssh"
    secret_dir: "{{ lookup('env', 'HOME') }}/.secrets" 
    personal: "{{ lookup('env', 'HOME') }}/personal"
    work: "{{ lookup('env', 'HOME') }}/work"
    username: "{{ lookup('env', 'USER') }}"
    dotfiles_dir: "{{ lookup('env', 'HOME') }}/.dotfiles"
  pre_tasks:
  - name: Update Apt
    when: ansible_os_family == "Debian"
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/secrets.yml
    - include: tasks/git.yml
    - include: tasks/docker.yml
      # Docker is installed with brew on macOS
      when: ansible_os_family == "Debian"
    - include: tasks/packages.yml
    - include: tasks/taskopen.yml
      # Taskopen is installed with brew on macOS
      when: ansible_os_family == "Debian"
    - include: tasks/mamba.yml
      # Mamba is installed with brew on macOS
      when: ansible_os_family == "Debian"
    - include: tasks/nvim.yml
      # Neovim is installed with brew on macOS
      when: ansible_os_family == "Debian"
    - include: tasks/lazygit.yml
      # Lazygit is installed with brew on macOS
      when: ansible_os_family == "Debian"
    - include: tasks/zsh.yml
    - include: tasks/stow.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/starship.yml
      # Starship is installed with brew on macOS
      when: ansible_os_family == "Debian"
  roles:
    - role: ecgalaxy.vscode
      include_vars:
        file: vars/vscode_extensions.yml
